"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x7duqo51i-l!i+cjw*r6$)7)awg#+m9%5-=g(l%qi^^l$svh=f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

env = environ.Env()
environ.Env.read_env()

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


CORE_APPS = [
    'korbo',
    'korbo.abstract',
    'korbo.extra',
    'korbo.user',
    'korbo.auth',
    'korbo.account',
    'korbo.account.consultant',
    'korbo.account.freelance',
    'korbo.account.startup',
    'korbo.account.staff',
   

]

THIRD_PARTY_APPS = [
    'rest_framework',
    'drf_spectacular',

]


INSTALLED_APPS += CORE_APPS+THIRD_PARTY_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "root.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "root.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "korbo"),
        "USER": os.getenv("DB_USER", "korbo"),
        "PASSWORD": os.getenv("DB_PASSWORD", "djehuty"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": "5432",
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


########################
#### KORBO SETTINGS ####
########################


KORBO_EMAILS = []
KORBO_STAFF_MEMBER = []

#################################
#### REST_FRAMEWORK SETTINGS ####
#################################

REST_FRAMEWORK = {

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    "DEFAULT_AUTHENTICATION_CLASSES": [
        #"korbo.auth.authentications.ConsumerJWTAuthentication",
        #"korbo.auth.authentications.ConsultantJWTAuthentication",
    ],
}

#################################
###### SPECTACULAR SETTINGS #####
#################################

SPECTACULAR_SETTINGS = {
    'TITLE': 'KORBO API',
    'DESCRIPTION': 'Korbo rating application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
  
}

#################################
########## JWT SETTINGS #########
#################################

JWT_SECRET = os.getenv("JWT_SECRET", "(luv&udxx$=ry1_9&tbh%x76uo7o#=*-93-riflngo$j6xgp7+")
JWT_TOKEN_VALIDITY_TIME = 30
JWT_REFRESH_TOKEN_VALIDITY_TIME = 30*2

AUTH_USER_MODEL = "korbo_user.User"
